export const AUDIT_ACTIONS = {
    AUTH_LOGIN_SUCCEEDED: 'auth.login_succeeded',
    AUTH_LOGIN_FAILED: 'auth.login_failed',
    AUTHZ_DENIED: 'authz.denied',
    TENANT_API_KEY_AUTH_FAILURE_INVALID_KEY: 'tenant.api-key.auth-failure.invalid-key',
    TENANT_API_KEY_AUTH_FAILURE_IP_BLOCKED: 'tenant.api-key.auth-failure.ip-blocked',
    PASSKEY_AUTHENTICATE_FAILED: 'passkey.authenticate-failed',
    API_MUTATION: 'api.mutation',
    APPLICATION_CREATE: 'application.create',
    APPLICATION_UPDATE: 'application.update',
    APPLICATION_DELETE: 'application.delete',
    USER_CREATE_BY_ADMIN: 'user.create-by-admin',
    USER_UPDATE: 'user.update',
    USER_DELETE: 'user.delete',
    ROLE_CREATE: 'role.create',
    ROLE_UPDATE: 'role.update',
    ROLE_DELETE: 'role.delete',
    CONTRACT_CREATE: 'contract.create',
    CONTRACT_UPDATE: 'contract.update',
    CONTRACT_ADDRESS_CHANGE: 'contract.address-change',
    CONTRACT_DELETE: 'contract.delete',
    CONTRACT_FUNCTION_PERMISSION_CREATE: 'contract-function-permission.create',
    CONTRACT_FUNCTION_PERMISSION_UPDATE: 'contract-function-permission.update',
    CONTRACT_FUNCTION_PERMISSION_DELETE: 'contract-function-permission.delete',
    CONTRACT_EVENT_PERMISSION_CREATE: 'contract-event-permission.create',
    CONTRACT_EVENT_PERMISSION_UPDATE: 'contract-event-permission.update',
    CONTRACT_EVENT_PERMISSION_DELETE: 'contract-event-permission.delete',
    TEMPLATE_CREATE: 'template.create',
    TEMPLATE_UPDATE: 'template.update',
    TEMPLATE_DELETE: 'template.delete',
    TEMPLATE_PERMISSION_CREATE: 'template-permission.create',
    TEMPLATE_PERMISSION_UPDATE: 'template-permission.update',
    TEMPLATE_PERMISSION_DELETE: 'template-permission.delete',
    TENANT_CREATE: 'tenant.create',
    TENANT_UPDATE: 'tenant.update',
    TENANT_DELETE: 'tenant.delete',
    API_KEY_AUTH_FAILURE_INVALID_KEY: 'api-key.auth-failure.invalid-key',
    API_KEY_CREATE: 'api-key.create',
    API_KEY_REVOKE: 'api-key.revoke',
    IP_WHITELIST_CREATE: 'ip-whitelist.create',
    IP_WHITELIST_DELETE: 'ip-whitelist.delete',
    SERVICE_CREATE: 'service.create',
    SERVICE_UPDATE: 'service.update',
    SERVICE_DELETE: 'service.delete',
    SESSION_REVOKE: 'session.revoke',
    SESSION_REVOKE_ALL: 'session.revoke-all',
    SESSION_REVOKE_OTHERS: 'session.revoke-others',
    SESSION_EXTEND: 'session.extend',
    PASSKEY_DELETE: 'passkey.delete',
    PASSKEY_ADMIN_RESET_ALL: 'passkey.admin-reset-all',
    PASSKEY_REGISTER_BEGIN: 'passkey.register-begin',
    PASSKEY_REGISTER: 'passkey.register',
    PASSKEY_UPDATE: 'passkey.update',
    PASSKEY_STEP_UP_BEGIN: 'passkey.step-up-begin',
    PASSKEY_STEP_UP_VERIFIED: 'passkey.step-up-verified',
    PASSKEY_STEP_UP_FAILED: 'passkey.step-up-failed',
    PASSKEY_STEP_UP_REJECTED: 'passkey.step-up-rejected',
    PASSKEY_STEP_UP_CONSUMED: 'passkey.step-up-consumed',
    WALLET_ASSOCIATE: 'wallet.associate',
    WALLET_DISASSOCIATE: 'wallet.disassociate',
    TENANT_USER_CREATE: 'tenant.user.create',
    AUTH_LOGOUT: 'auth.logout',
    WALLET_TOKEN_INVALIDATE: 'wallet-token.invalidate',
    TRANSACTION_ALLOWANCE_CREATE: 'transaction-allowance.create',
    TRANSACTION_ALLOWANCE_UPDATE_HASH: 'transaction-allowance.update-hash',
    M2M_APP_CREATE: 'm2m-app.create',
    M2M_APP_UPDATE: 'm2m-app.update',
    M2M_APP_DELETE: 'm2m-app.delete',
    M2M_APP_API_KEY_AUTH_FAILURE_INVALID_KEY: 'm2m-app.api-key.auth-failure.invalid-key',
    M2M_APP_API_KEY_AUTH_IP_BLOCKED: 'm2m-app.api-key.auth-failure.ip-blocked',
    ORGANIZATION_CREATE: 'organization.create',
    ORGANIZATION_UPDATE: 'organization.update',
    ORGANIZATION_DELETE: 'organization.delete',
    ORGANIZATION_USER_ADD: 'organization.user.add',
    ORGANIZATION_USER_REMOVE: 'organization.user.remove',
    ORGANIZATION_USER_ROLES_UPDATE: 'organization.user.roles.update',
    ORGANIZATION_OIDC_PROVIDER_SET: 'organization.oidc-provider.set',
    ORGANIZATION_OIDC_PROVIDER_DELETE: 'organization.oidc-provider.delete',
    ORGANIZATION_PENDING_ADMIN_ADD: 'organization.pending_admin.add',
    ORGANIZATION_PENDING_ADMIN_REMOVE: 'organization.pending_admin.remove',
    ORGANIZATION_ADMIN_ADD: 'organization.admin.add',
    ORGANIZATION_ADMIN_REMOVE: 'organization.admin.remove',
    ORGANIZATION_BRANDING_UPDATE: 'organization.branding.update',
    ORGANIZATION_SIWE_SETTINGS_UPDATE: 'organization.siwe-settings.update',
    ORGANIZATION_SESSIONS_REVOKE: 'organization.sessions.revoke',
    M2M_APP_USER_CREATE: 'm2m-app.user.create',
    M2M_APP_WALLET_ASSOCIATE: 'm2m-app.wallet.associate',
    FAUCET_CLAIM: 'faucet.claim',

    // Deprecated
    DEPRECATED_TENANT_API_KEY_CREATE: 'tenant.api-key.create',
    DEPRECATED_TENANT_API_KEY_REVOKE: 'tenant.api-key.revoke',
    DEPRECATED_TENANT_IP_WHITELIST_CREATE: 'tenant.ip-whitelist.create',
    DEPRECATED_TENANT_IP_WHITELIST_DELETE: 'tenant.ip-whitelist.delete'
} as const;

export type CoreAuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

/** Listing a feature's actions here would publish its surface through the OpenAPI spec. */
export type FeatureAuditAction = `${string}.${string}`;

export type AuditActionType = CoreAuditAction | FeatureAuditAction;

export const AUDIT_ACTION_TYPES = Object.values(AUDIT_ACTIONS) as [CoreAuditAction, ...CoreAuditAction[]];
